<?php
/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */

JFormHelper::loadFieldClass('predefinedlist');

class JFormFieldReason extends JFormFieldPredefinedList
{
	protected $type = 'PerformedType';

	protected $predefinedOptions = array(
		COM_CONTROLCARD_REASON_VALUE_1,
		COM_CONTROLCARD_REASON_VALUE_2,
		COM_CONTROLCARD_REASON_VALUE_3,
		COM_CONTROLCARD_REASON_VALUE_4,
		COM_CONTROLCARD_REASON_VALUE_5,
		COM_CONTROLCARD_REASON_VALUE_6,
		COM_CONTROLCARD_REASON_VALUE_7,
		COM_CONTROLCARD_REASON_VALUE_8,
		COM_CONTROLCARD_REASON_VALUE_1,
		COM_CONTROLCARD_REASON_VALUE_2,
		COM_CONTROLCARD_REASON_VALUE_3,
		COM_CONTROLCARD_REASON_VALUE_4,
		COM_CONTROLCARD_REASON_VALUE_5,
		COM_CONTROLCARD_REASON_VALUE_6,
		COM_CONTROLCARD_REASON_VALUE_7,
		COM_CONTROLCARD_REASON_VALUE_8,
		COM_CONTROLCARD_REASON_VALUE_1,
		COM_CONTROLCARD_REASON_VALUE_2,
		COM_CONTROLCARD_REASON_VALUE_3,
		COM_CONTROLCARD_REASON_VALUE_4,
		COM_CONTROLCARD_REASON_VALUE_5,
		COM_CONTROLCARD_REASON_VALUE_6,
		COM_CONTROLCARD_REASON_VALUE_7,
		COM_CONTROLCARD_REASON_VALUE_8,
		COM_CONTROLCARD_REASON_VALUE_9
	);

}